# Generated by Django 2.0.6 on 2018-06-27 07:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='adults',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='children',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='enq_date_end',
            field=models.DateField(default=datetime.date(2018, 7, 5)),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='enq_date_start',
            field=models.DateField(default=datetime.date(2018, 6, 28)),
        ),
    ]
