# Generated by Django 2.0.6 on 2018-06-27 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0004_auto_20180627_0710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='enq_date_end',
            field=models.DateField(default=datetime.date(2018, 7, 5)),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='enq_date_start',
            field=models.DateField(default=datetime.date(2018, 6, 28)),
        ),
    ]
