# Generated by Django 2.0.6 on 2018-06-28 16:02

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc
import enquiries.models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0005_auto_20180627_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='adults',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='children',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='email',
            field=models.EmailField(max_length=80),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='enq_date_end',
            field=models.DateField(default=datetime.datetime(2018, 7, 6, 16, 2, 55, 54144, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='enq_date_start',
            field=models.DateField(default=datetime.datetime(2018, 6, 29, 16, 2, 55, 54076, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
