# Generated by Django 2.0.6 on 2018-06-28 16:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0006_auto_20180628_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='enq_date_start',
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='enq_date_end',
            field=models.DateField(default=datetime.datetime(2018, 7, 6, 16, 32, 57, 611144, tzinfo=utc)),
        ),
    ]
