# Generated by Django 2.0.6 on 2018-06-28 16:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0007_auto_20180628_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='enq_date_start',
            field=models.DateField(default=datetime.datetime(2018, 6, 29, 16, 33, 16, 739972, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='enq_date_end',
            field=models.DateField(default=datetime.datetime(2018, 7, 6, 16, 33, 16, 740032, tzinfo=utc)),
        ),
    ]
