# Generated by Django 2.0.6 on 2018-06-29 06:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0008_auto_20180628_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='enq_date_end',
            field=models.DateField(default=datetime.datetime(2018, 7, 7, 6, 50, 48, 41558, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='enq_date_start',
            field=models.DateField(default=datetime.datetime(2018, 6, 30, 6, 50, 48, 41495, tzinfo=utc)),
        ),
    ]
