# Generated by Django 2.0.6 on 2018-06-29 07:20

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0009_auto_20180629_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='enq_date_end',
            field=models.DateField(default=datetime.datetime(2018, 7, 7, 7, 20, 41, 580315, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='enq_date_start',
            field=models.DateField(default=datetime.datetime(2018, 6, 30, 7, 20, 41, 580262, tzinfo=utc)),
        ),
    ]
