# Generated by Django 2.0.6 on 2018-07-01 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0010_auto_20180629_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='enq_date_end',
            field=models.DateField(default=datetime.datetime(2018, 7, 9, 16, 8, 29, 901837)),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='enq_date_start',
            field=models.DateField(default=datetime.datetime(2018, 7, 2, 16, 8, 29, 901787)),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='sent_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
