# Generated by Django 2.0.6 on 2018-07-01 16:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0011_auto_20180701_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='enq_date_end',
            field=models.DateField(default=datetime.datetime(2018, 7, 9, 16, 11, 31, 249568)),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='enq_date_start',
            field=models.DateField(default=datetime.datetime(2018, 7, 2, 16, 11, 31, 249463)),
        ),
    ]
